import "./global.css";
import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";

const nextFont = Roboto_Slab({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nextFont.className}>{children}</body>
    </html>
  );
}
